namePrefix: staging-
commonLabels:
  variant: staging
patchesStrategicMerge:
- config-map.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: hello-python
  newName: billygoo/hello-python
  newTag: ba9a29f40490d1df7326fb024e1bd37750d803f0
