namePrefix: staging-
commonLabels:
  variant: staging
patchesStrategicMerge:
- config-map.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: billygoo/hello-python
  newName: billygoo/hello-python
  newTag: 0d340ba226556132da8726f80d12ba77fe912163
- name: hello-python
  newName: billygoo/hello-python
  newTag: ba9a29f40490d1df7326fb024e1bd37750d803f0
