commonLabels:
  variant: canary-release
resources:
- config-map.yaml
- rollout.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: billygoo/hello-python
  newName: billygoo/hello-python
  newTag: 70986a9e153ccf9a3122b0937c5e354e6b807fed
