apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-python
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: billygoo/hello-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: VARIANT
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: staging
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      stableService: hello-python-stable
      canaryService: hello-python-canary
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause:
          duration: 30s # 30 seconds
      # - setWeight: 100
      - pause: {}
