apiVersion: v1
kind: Service
metadata:
  name:  hello-python-stable
  labels:
    app:  hello-python
spec:
  ports:
  - port: 6000
    targetPort: 5000
  selector:
    app:  hello-python
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  hello-python-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
spec:
  rules:
  - host: "test.billygoo.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-python-stable
            port:
              number: 80