commonLabels:
  app: hello-python

resources:
- config-map.yaml
- deployment.yaml
- service.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hello-python
  newName: billygoo/hello-python
  newTag: 2e239d86aede4b40e75b9334892b3dc56e7a5b97
